name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1'  # Setiap Senin pukul 00:00 UTC

jobs:
  security:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./FlightBooking2/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: ./FlightBooking2/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level moderate

      - name: Attempt to fix vulnerabilities
        run: npm audit fix

      - name: Check outdated packages
        run: npm outdated || true
